name: CI-CD

on:
    push:
      branches: ["main"]


jobs:
    CI:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4.2.2

        - name: Autentica no DockerHub
          uses: docker/login-action@v3.4.0
          with: 
            password: ${{secrets.PAT_DOCKERHUB}}
        
        - name: Construção Img docker
          uses: docker/build-push-action@v6.16.0
          with:
            context: ./src
            file: ./src/Dockerfile
            push: true
            tags:
                samuelsouza/live-kube-news:v1
                samuelsouza/live-kube-news:latest
            
